# Generated by Django 2.2 on 2019-04-10 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('project_location', models.CharField(max_length=100)),
                ('project_time1', models.DateTimeField()),
                ('project_time2', models.DateTimeField()),
                ('project_map', models.CharField(max_length=100)),
                ('project_introduction', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
