# Generated by Django 2.2 on 2019-04-10 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_host',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(default='', max_length=100),
        ),
    ]
