# Generated by Django 2.2 on 2019-04-11 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20190411_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_introduction',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
