# Generated by Django 2.2.1 on 2019-05-30 00:47

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20190411_2137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_map',
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_data', jsonfield.fields.JSONField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project', verbose_name='project')),
            ],
        ),
    ]
