# Generated by Django 2.2.1 on 2019-06-04 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20190530_0847'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(default='', max_length=100)),
                ('activity_name', models.CharField(default='', max_length=100)),
                ('activity_location', models.CharField(default='', max_length=100)),
                ('activity_time1', models.DateTimeField()),
                ('activity_time2', models.DateTimeField()),
                ('activity_host', models.CharField(default='', max_length=100)),
                ('activity_introduction', models.CharField(default='', max_length=1000)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project', verbose_name='project')),
            ],
        ),
    ]
