# Generated by Django 2.2.1 on 2019-06-04 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.CharField(default='', max_length=100)),
                ('host_address', models.CharField(default='', max_length=100)),
                ('host_introdection', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
