# Generated by Django 2.2.1 on 2019-06-04 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='host_email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='host',
            name='host_password',
            field=models.CharField(default='', max_length=100),
        ),
    ]
