# Generated by Django 2.2.1 on 2019-06-04 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20190604_1046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='host',
            old_name='host_introdection',
            new_name='host_introduction',
        ),
    ]
