# Generated by Django 2.2.1 on 2019-06-04 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20190604_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='host',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='projects.Host', verbose_name='host'),
            preserve_default=False,
        ),
    ]
