# Generated by Django 2.2.1 on 2019-06-05 03:27

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20190605_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.CharField(default='1', max_length=100)),
                ('map_data', jsonfield.fields.JSONField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Activity', verbose_name='activity')),
            ],
        ),
        migrations.CreateModel(
            name='MapDetailPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detailpage_name', models.CharField(default='', max_length=100)),
                ('map_data', jsonfield.fields.JSONField()),
                ('mapPoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.MapPoint', verbose_name='mappoint')),
            ],
        ),
    ]
