# Generated by Django 2.2.1 on 2019-06-07 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_comment_hotactivity_queryactivity_queryproject_tourist'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(default='', max_length=100)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
    ]
