# Generated by Django 2.2.1 on 2019-06-08 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_hotproject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map',
            name='activity',
        ),
        migrations.AddField(
            model_name='map',
            name='project',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='projects.Project', verbose_name='project'),
        ),
    ]
