# Generated by Django 2.2.1 on 2019-06-08 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_auto_20190608_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotactivity',
            name='activity_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='hotproject',
            name='project_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
