# Generated by Django 2.2.1 on 2019-06-12 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_mapdetailedpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_image_url',
            field=models.CharField(default='', max_length=100),
        ),
    ]
