# Generated by Django 2.2.1 on 2019-06-12 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_project_project_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_image_url',
            new_name='project_image_name',
        ),
        migrations.AddField(
            model_name='activity',
            name='activity_image_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
