# Generated by Django 2.2.1 on 2019-06-13 11:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_auto_20190612_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 13, 11, 48, 1, 605478, tzinfo=utc)),
        ),
    ]
