# Generated by Django 2.2.1 on 2019-06-16 03:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_project_created_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 16, 3, 16, 10, 943934, tzinfo=utc)),
        ),
    ]
